export const MUTATATION_ADD_TODO = 'ADD_TODO';
export const MUTATATION_CLEAR_ALL_TODOS = 'CLEAR_ALL_TODOS';
export const MUTATATION_REMOVE_TODO = 'REMOVE_TODO';
export const MUTATATION_SET_ALL_TODOS = 'SET_ALL_TODOS';
export const MUTATATION_SET_LOADING_STATUS = 'SET_LOADING_STATUS';
